### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dancychen** [tirthajyoti/pydbgen#16]
#from pydbgen import pydbgen
myDB=pydbgen.pydb()
testdf= myDB.gen_data_series(data_type='data')
print(testdf)

=====================

Traceback (most recent call last):
  File "D:/python/Demopycharm/Test_month/z2020_01_month/Data-collect.py", line 40, in <module>
    testdf= myDB.gen_data_series(data_type='data')
  File "D:\python\Demopycharm\Myspider\venv\lib\site-packages\pydbgen\pydbgen.py", line 191, in gen_data_series
    fake.seed(self.seed)
  File "D:\python\Demopycharm\Myspider\venv\lib\site-packages\faker\proxy.py", line 79, in __getattribute__
    raise TypeError(msg)
TypeError: Calling `.seed()` on instances is deprecated. Use the class method `Faker.seed()` instead.

**Comment by AyushTanwar** [comment]
I am facing the same problem

**Comment by aahventures** [comment]
Try force installing an older version of Faker
```
pip install Faker==2.0.5
```

**Comment by kvrameshreddy** [comment]
add this import "from faker import Faker"
and change "fake" to "Faker"
Faker.seed(self.seed)

**Comment by kbowerma** [comment]
Can you expand on that last part @kvrameshreddy?

This is line 12-13
```python
   self.fake=Faker()
   self.seed-seed
```

should change to waht?

**Comment by kvrameshreddy** [comment]
![query](https://user-images.githubusercontent.com/49742709/88058577-45c54f80-cb81-11ea-9698-c78206772809.JPG)

I haven't faced any issue at line 12-13. my issue appeared at line 191-192. so i changed accordingly which worked for me.

**Comment by kbowerma** [comment]
Thanks but now I get:
```NameError: name 'Faker' is not defined```

**Comment by kvrameshreddy** [comment]
Share the code changes you made

**Comment by kbowerma** [comment]
Here it is:
```
else:
            import pandas as pd
            num=int(num)
            fake=self.fake
            Faker.seed(self.seed)
            lst = []
```

No worries,  I am just using Faker directly

**Comment by kvrameshreddy** [comment]
Add this line: "from faker import Faker" after pandas import then it will work fine
