### ISSUE TITLE
FileNotFoundError in  db.realistic_email()

### ISSUE THREAD

**Issue by drednout** [tirthajyoti/pydbgen#5]
I've installed pydbgen using pip into venv and received FileNotFoundError for realistic email generator: 
```
>>>  import pydbgen
>>> from pydbgen import pydbgen
>>> myDB=pydbgen.pydb()

>>> for _ in range(10):
...     print(db.realistic_email('Tirtha Sarkar'))
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/dr/devel/pydbgen/venv/lib/python3.6/site-packages/pydbgen/pydbgen.py", line 99, in realistic_email
    fh = open(path)
FileNotFoundError: [Errno 2] No such file or directory: 'Domains.txt'

```
Version:
```
─$ venv/bin/pip freeze | grep pydbgen
pydbgen==1.0.5
```

**Comment by richardliu44** [comment]
try to copy Python_Install_Path\Lib\site-packages\pydbgen\Domains.txt to the folder that the python script  is placed.

**Comment by tirthajyoti** [comment]
@richardliu44 's solution is correct. The file should be in the same directory.
Closing now.
